theme = "meliora"

[editor]
line-number = "relative"
scrolloff = 2
bufferline = "always"

[editor.gutters.line-numbers]
min-width = 1

[editor.gutters]
layout = ["line-numbers", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"

