[ghostty.files]
"ghostty/config" = "~/.config/ghostty/config"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"

[niri.files]
"niri/config.kdl" = "~/.config/niri/config.kdl"

[noctalia.files]
"noctalia/colors.json" = "~/.config/noctalia/colors.json"
"noctalia/settings.json" = "~/.config/noctalia/settings.json"

[sunsetr.files]
"sunsetr/sunsetr.toml" = "~/.config/sunsetr/sunsetr.toml"

[vim.files]
"vim/.vimrc" = "~/.vimrc"
"vim/colors/" = "~/.vim/colors/"

[wofi.files]
"wofi/config" = "~/.config/wofi/config"
"wofi/style.css" = "~/.config/wofi/style.css"

[fuzzel.files]
"fuzzel/fuzzel.ini" = "~/.config/fuzzel/fuzzel.ini"

[zed.files]
"zed/keymap.json" = "~/.config/zed/keymap.json"
"zed/settings.json" = "~/.config/zed/settings.json"
"zed/tasks.json" = "~/.config/zed/tasks.json"

[nvim.files]
"nvim/init.lua" = "~/.config/nvim/init.lua"
"nvim/lazy-lock.json" = "~/.config/nvim/lazy-lock.json"

[fastfetch.files]
"fastfetch/config.jsonc" = "~/.config/fastfetch/config.jsonc"
